# Filebeat configuration file
# Documentation: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-overview.html
# Filebeat version: 8.17.4

#output.logstash:
 # hosts: ["logstash:5044"]

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log  # Ensure this path contains logs
  fields:
    log_type: application
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  bulk_max_size: 50
  backoff.init: 1s
  backoff.max: 60s

logging.level: debug
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644


